artifact_uri: file:///home/mle-user/mle-mlflow/mlflow_experiments_store/0/71da46acc23a40409dc41af7b560d406/artifacts
end_time: 1726503697080
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 71da46acc23a40409dc41af7b560d406
run_name: Default
run_uuid: 71da46acc23a40409dc41af7b560d406
source_name: ''
source_type: 4
source_version: ''
start_time: 1726503697073
status: 4
tags: []
user_id: mle-user
