artifact_uri: file:///home/mle-user/mle-mlflow/mlflow_experiments_store/0/e0c8e671bd1a4b06bfbb1735c18dd83e/artifacts
end_time: 1726504269361
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e0c8e671bd1a4b06bfbb1735c18dd83e
run_name: Default
run_uuid: e0c8e671bd1a4b06bfbb1735c18dd83e
source_name: ''
source_type: 4
source_version: ''
start_time: 1726504269336
status: 3
tags: []
user_id: mle-user
