artifact_uri: file:///home/mle-user/mle-mlflow/mlflow_experiments_store/0/3046880d8d9c4369bcadb1f9d7a2d0d8/artifacts
end_time: 1726504118734
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3046880d8d9c4369bcadb1f9d7a2d0d8
run_name: Default
run_uuid: 3046880d8d9c4369bcadb1f9d7a2d0d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1726504118709
status: 3
tags: []
user_id: mle-user
